Repository a2ap/a2a4j, pull requests merged in 2025-06, with the labels that each got.

#9 [doc] add contribution doc and update readme
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/question.md
  .github/PULL_REQUEST_TEMPLATE.md
  CONTRIBUTING.md
  README.md
  README_CN.md
  a2a4j-core/README.md
  a2a4j-core/README_CN.md
  a2a4j-samples/server-hello-world/README.md
  a2a4j-samples/server-hello-world/README_CN.md
  a2a4j-spring-boot-starter/a2a4j-server-spring-boot-starter/README.md
  a2a4j-spring-boot-starter/a2a4j-server-spring-boot-starter/README_CN.md
  a2a4j-spring-boot-starter/a2a4j-server-spring-boot-starter/STARTER_API.md
Labels: area/infra

#20 [refactor] update a2a client and test deploy to maven central
  .github/workflows/build-and-test.yml
  a2a4j-core/src/main/java/io/github/a2ap/core/client/impl/DefaultA2aClient.java
  pom.xml
Labels: area/infra

#33 [docs] Fix minor typos and a doc link
  CONTRIBUTING.md
  CONTRIBUTING_CN.md
  README_CN.md
Labels: area/infra, good first pr

#40 [feat] Support AuthenticatedExtendedCard
  a2a4j-core/src/main/java/io/github/a2ap/core/model/AgentCard.java
  a2a4j-core/src/main/java/io/github/a2ap/core/server/A2AServer.java
  a2a4j-core/src/main/java/io/github/a2ap/core/server/impl/DefaultA2AServer.java
  a2a4j-samples/server-hello-world/pom.xml
  a2a4j-samples/server-hello-world/src/main/java/io/github/a2ap/server/hello/world/controller/A2AServerController.java
  a2a4j-samples/server-hello-world/src/main/resources/application.yml
  a2a4j-samples/server-hello-world/src/test/java/io/github/a2ap/server/hello/world/controller/A2AServerControllerTest.java
  a2a4j-spring-boot-starter/a2a4j-server-spring-boot-starter/src/main/java/io/github/a2ap/server/spring/auto/configuration/A2AServerAutoConfiguration.java
  a2a4j-spring-boot-starter/a2a4j-server-spring-boot-starter/src/main/java/io/github/a2ap/server/spring/auto/configuration/A2AServerProperties.java
Labels: good first pr, feature
